language: node_js
node_js:
  - 9
branches:
  only:
  - master
env:
  global:
    - "BAT_EYESHADE_SERVER=http://localhost:3002"
    - "BAT_GRANT_SERVER=http://localhost:3333"
    - "BAT_HELPER_SERVER=http://localhost:3004"
    - "BAT_LEDGER_SERVER=http://localhost:3001"
    - "BAT_SETTLEMENT_ADDRESS=6654ecb0-6079-4f6c-ba58-791cc890a561"
    - "DEBUG=*,-babel,-eslint:*,-mongo:*,mongo:queries"
    - "GRANT_SIGNATOR_PUBLIC_KEY=bbe028009e744422bfc39b0e226633324d8c5fe0744c87c1018b88a488bc5899"
    - "GRANT_WALLET_CARD_ID=f042845f-fa62-4022-8117-a476ec583a7b"
    - "MONGODB_URI=mongodb://mongo/test"
    - "NODE_ENV=development"
    - "NODE_PATH=."
    - "REDEEMER_TOKEN=foobarfoobar"
    - "REDEEMER_URL=http://grant-web:3333"
    - "REDEEMER_URL=http://grant-web:3333"
    - "REDIS_URL=redis://redis:6379"
    - "TESTING_COHORTS=test"
    - "TOKEN_LIST=foobarfoobar"
    - "UPHOLD_DONOR_CARD_ID=6654ecb0-6079-4f6c-ba58-791cc890a561"
    - "VOTING_COHORTS=control,grant,test"
    - secure: "JQ9WipBrcCPtXFwv/fmzhv8LPz/tx/jCPpeTK0KmSZr4Yqs5kMG0YGH3QeT1YDpiRakW9X5us9tsnsfHuslvZ8Z565lc0wIK7b7CUcEzVuBts6cfVQtOpqKKYjw6jyq5TraTYawYGUfeaCkP+35oM/1fs4vPy6MbH5Plzg6f9iMfB+BFysRT20JYKXcW0LfihHRKStaAJYKDD2mpdY4kStu7vYB66LgR6Solw1IUwgJzfKst/dM6PJspfmNkFaHCoBNMEYcUJmeJPqmLCnfIA+eRCrSMfHOChjzCV6JbmcD11FOydISEhdt67X+5TDArePYVssrj7NygVlrn8TOvk6InXuul6n+oIpS0vz5e5QdxrReLLwb+WJPK7xKWD56Ko2gfTwtEUdevLzQhKfPMs5wW5ujjlcjAqi5PmC87Q+bxCjet19EdJ4j09y2NSKRo1LMzu1WIM6o1mIatha0vJEHa05XAUsuD9lCGrt/aG4DLYh5Q5gJP/SYDoMl+wJku254KJN+WesxaSREhgdqtV13GFnMofI9r/vq4wKrlcbsMh3UD337NZlNVZzONINeJ4afN3TRK+LS8bHGsss/ZpLcnfT0uYMXzneQQhkKmKWkss8VOLEZ2ccLRG0LNWsOJXznBE/SqXaxSK4NkgXQDyfVUuAj7GPyIDX6hygsguyA="
    - secure: "be8ASUNkGT1MpO/wfwVQKuo0Absf5xQAnjXRmsrM105n+vGXdq1c/fl13wow7d/PQtR27tNlJ5UmoeROUCBLlOKm+bWWZ7wFThsxOQtHk3yJoaVtIApo5cwEQcMi/92zWQKDwO7ZuK+xY9oLiYng2yayfuxBUEzWlNxS0cMsmq6Xnf1qG8USVCqvo8gQp/X8hliscFWRbCJ+lzggmlIsoTe6RElF9N3yXngvWRJY/GDjOe3FD2wJNDoE8wYwHcxKvfcdL0c8dWhHl5KC366ZSiBMJHrwv2aVjUgwQ2Azsdehxy1bsqyiH2bS/ifH8FUosjMA/g8qRB89EgaLCS5NndIVl1q0miuRv20kMaF6syTOH3HyDi/o2L9tg1Z/XSuNSVI2o+A8yJfKiY1AwjCR8aQ+uyKj9kOg7nTlBElHrOcAOaiC0Rg13TZ2230IbFanQFIqDL0B8xQx1EAxsArgWIrebqSd1QbVYKEHE5+2dWXExPX+7e217rFvEz5Ltxq1U9IdHHnmcTxUrylr800ub2PtOyZvRNbBFXq5tDpENLl/lV8yf0Qm2q+8jUvqXZIG0akIqC5b0cpHEtxJcAGvfqFx8vZUV1WW4TVbxApmndSGFw2bF6psx6SJUDrdFfl87u1Rb7wWtesDXAMrfIphlr0AcH2P7XDqxAjifuQgtdk="
    - secure: "I9ELp+dcTBczYT/XHh7eRVKC2ikkJv+yFCGJE3pLsZaW6aSkDt7KgaX3Rivrlt1pqHL53Cmv0F9qfyQR9PNl1zu7XdBiHcOSbLYI1bwnDlNve2opJoGipECuMbp9r6+GOxgnX5mQivJ5ZxTlhboHStBBxD1lLOriUTOMNfpEckJmaZ5nxedTUdmdEnXRCTZpHgsB345NVXAmEePp8L+KXWnhWYVnhCVmwdxq3xl9p/9ZaP6E3AF7syemWIKbSCCPDS/tJrysNouuJ9YlX0oi+rcl/GPgCdouBu/94orqAzVAFdfNX1taooRtNOgvkpIp7Q2mS3xphRSj+ZEijwnNwuIbNososVhvRRvNiFtumQG7Oe/TuYjUHo0I4Y2ZfKH+UB3Gw3CrnLSbyCKxglHEzFU8TWO1tsm/mj/qvvPw6cgUVpZUkDnAS28wTfzu3RxryYjn4Jg02eHlg4RIKCIJmBuldEyJtlO+XyzZajf+XenU2MxulVlk8dU3goQ7xM7uuVy1DAT3npPa8eHGwCD5Kd4vEuCTgPA55cwI/zKTlaskZKq1kmes2AN+9PStJEpt7u6ITD1+zsS7Ot82gmK2NKgA1tm6r7WtLnLL1SgflNxuGFeJVQN0Ix2KEZhma5xGkv1S433aiBV0xiiaLzzpVHaD+d3TdNCM2oaIL6v1LZM="
    - secure: "Flt+fCZMubcyqCbKntaPvmxyJ2gix8wCIcBa0yE82lQ3lzXgmOZLE1x7V0HssCnuXsLe7CA4wrqKk7aMpNcNpzhgghroZZ1K3zKf2DXg8T0GJqombMrHpoHUzTEIK9iojXYBvkaVqK/vYLbrel2dkJDWER0dUP00wwAgTCTm+W6IzTDUGDaah31Xann+gFbu++1L8zdDQNXW2XOmpuLQ141/NV1vZBuAi7I6ORf43vOLziIl443s+DepcODXQMawX/HMzwMuMS1RQcxAkIt9EKF0E5UpEqoJdD1KY5/5v3OzPi7w8e/D/wdGvIwXTwLPR6ZgLexNdEgr/B36CLc22RSJOa3IMrDjoETRGbVO0gCLuDeYgwWAoYpp6DMqP5DGoZlcssuhkd8Q5OPpK3tD1kHwJwB0SSGmCJ/c2KlSjxoKQs9tdq3900bu8ETHOfR7vyR+qmZTj2lHRpRLwsaN7KqnQzWAJu2qs5m5/AJYHeDATFy+VCQh/gvg1mrToWVxKS+gWQfXdfTm/UK+zE3fJTMD7qkp6l7QNbhTQNVLFJlty1W/Bx65KEgVs8WzlM/nWRaYlln/lu8vbZAZdmGrpjQzkcqy8oT4d3u0ZVoDNEu0F/wY0PBxw2DIqi3TZTThbGYz7T1oBeBONEBr5XBIRFmaMuNVamxPzKJiSoiFKu4="
    - secure: "vFqXh+FeAYsgtSyvEozHOcQgTdqxZpHFZ+AUH9JYe1X5cYWI+Yi4vhfL+BGirDLufuGyx6xfMTuacB3fNt6wl4oMdH8UJ/Kj7FYtNFeiWL7F81w9ux7HvQo1KA6YQb+O4xKfjUgRbSdvpVIWBpmSBdZMHc7l3e9eLGUzh5Xkr/KAFeg3FT+9/VVHvVmir0mmPxzw8dbk3PcK6lSb6aY4Q9shIVLST46v2MilduYIxIjzSq7MhrwZkek8RSarWrXIX614UDBhYYh/UbfuzGtobovLSqjgO5JdskTWHagE/MER0fmB2s7BE57OfH6wgRaFeUy6YrLtDl2BkYRWXxHGCALnuJcDQfKEdPRayIzLOAsSXMbTI5gxj/6izzkRyTaomi2wjk0ZZxJIZYmnK5IKG3an6SlCTb2HnlT8tAlJRvh9c+Kh1TQY4hzmJUj74pmCe4gxkCRuOi75gAT8eJIfZO/jTuDxXb7MumHowOZOOberBOQXVkffWdsE8bv7AaMhTRTqYmv751HmMBj++m33nP4Ex7Zvm9lZrcPyw7M1IMVTvVn4dNI/a2oUxkvUJvn/BM2YSnl6ez2GFyi/lPErlfs651DmU2juOcznISP06G0wXWC2TWB+5YGlv11ST7VKUlp2FtG7mUNlU3ptpZxThf9EB5wT5jYuL4YRa0NzfhY="
services:
  - mongodb
  - redis-server
  - docker
cache:
  directories:
    - $HOME/.npm
before_install:
  - npm i --global npm@5.8.0
  - npm --version
sudo: required
before_script:
  # lint the files (fail early)
  - npm run lint
  # sometimes travis takes a while to bring up mongo
  - sleep 15
  # build docker image
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # pull the bat go layer
  - docker pull brave/bat-go:latest
  # build the docker compose file
  - docker-compose build
  # bring up the relevant services
  - npm run docker-up-detached
  # let the detached up command start up
  - sleep 20
  # put surveyor into docker
  - npm run create-surveyor
  # put promotion into docker
  - npm run create-promotion
after_success: npx codecov --file=./coverage/lcov.info
