version: "2.1"

services:
  captcha-web:
    container_name: captcha-web
    image: bat-captcha:latest
    ports:
      - "3334:3334"
    environment:
      - "ALLOW_DEBUG_APK=1"
      - "IGNORE_APK_DIGEST=1"
      - TOKEN_LIST
    networks:
      - eyeshade
